//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Central_de_Artigos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artigos
    {
        public int id { get; set; }
        public string titulo { get; set; }
        public string conteudo { get; set; }
        public int categoriaId { get; set; }
        public Nullable<System.DateTime> data_publicacao { get; set; }
        public string status { get; set; }
    }
}
